# Generated by Django 2.0.7 on 2018-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nstracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_Type', models.CharField(max_length=100)),
                ('Path', models.CharField(blank=True, max_length=100)),
                ('Pin', models.CharField(blank=True, max_length=100)),
                ('Prog', models.CharField(blank=True, max_length=100)),
                ('Open_Id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
